### PR TITLE
fix: upstream project version to 2.2.6.SP1

### PR DESCRIPTION
**Pull request by jacobdotcosta**

### CODE REVIEW

**Review by metacosm — APPROVED** [review]

**Comment by jacobdotcosta** [comment]
@iocanel I think we overwritten the `fmp` version at your request. Because of it our CircleCI tests fail I tried removing it and they now pass. Could you please check if I need to put back the `fmp` version to `4.4.0`, and if we could do anything in order for the tests to succeed?

Thanks.

**Comment by iocanel** [comment]
Just to clarify...

I didn't request a version change for fmp.

I used 4.4.0 version of fmp as a workaround to build failures I had in the rest example. 
Use whatever version works for you.

**Comment by jacobdotcosta** [comment]
> Just to clarify...
> 
> I didn't request a version change for fmp.
> 
> I used 4.4.0 version of fmp as a workaround to build failures I had in the rest example.
> Use whatever version works for you.

I thought you requested the change, my mistake then.

**Comment by jacobdotcosta** [comment]
> > Just to clarify...
> > I didn't request a version change for fmp.
> > I used 4.4.0 version of fmp as a workaround to build failures I had in the rest example.
> > Use whatever version works for you.
> 
> I thought you requested the change, my mistake then.

I undo this removal because this FMP seems to be required for OCP4.

**Pull request merged**
