### PR TITLE
feat: use Spring liveness/readiness probes

### PR DESCRIPTION
**Pull request by aureamunoz**
Can you take a look to this also @gytis ? It's about using the spring liveness/readiness probes.

Related to #55 

Thanks!

### CODE REVIEW

**Comment by gytis** [comment]
Looks like something is wrong with the CircleCI config for the 2.3.x branch

**Comment by gytis** [comment]
The change itself looks good but we need to take care of the ci

**Comment by gytis** [comment]
The CI problem is that it expects `spring-boot-bom` to have a tag that is the same as the `snowdrop-dependencies` version use in this example. Until we have a first 2.3.x release we could modify the CircleCI config to checkout the `sb-2.3.x` branch instead of a tag here https://github.com/snowdrop/health-check-example/blob/sb-2.3.x/.circleci/config.yml#L35.

**Comment by aureamunoz** [comment]
Yes, exactly, it's because we have not released yet the `spring-boot-bom`. I will do it.

**Comment by gytis** [comment]
We should do the CI change in a separate commit, so that we could easily revert it later.

**Comment by gytis** [comment]
The example uses `snowdrop-dependencies` 2.3.1-SNAPSHOT but the actual version is 2.3.0-SNAPSHOT

**Comment by aureamunoz** [comment]
Yes, I did the change [here](https://github.com/snowdrop/spring-boot-bom/pull/110) Can you please, @gytis, review it?

**Comment by gytis** [comment]
I looks good to me. But if you plan to merge the https://github.com/snowdrop/spring-boot-bom/pull/110 soon I'd suggest to do it before this PR. Then we could verify that the example CI works.

**Comment by aureamunoz** [comment]
I think we can finally merge this one, right @gytis ?

**Comment by gytis** [comment]
I think so

**Pull request merged**
