### PR TITLE
chore: updates arquillian cube dependencies.

### PR DESCRIPTION
**Pull request by hemanik**

### CODE REVIEW

**Comment by geoand** [comment]
@gytis, This looks good to me, could you also take a look?

**Comment by gytis** [comment]
LGTM

**Comment by geoand** [comment]
Thanks for your help on this @hemanik!

Would it be possible for you to issue the PRs containing the same fix, against the `redhat` branch of the boosters as well?

**Comment by geoand** [comment]
Closing since this is very old

**Pull request closed without merging**
